//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HY.Frame.Bis
{
    using System;
    using System.Collections.Generic;
    
    public partial class com_person_view
    {
        public System.Guid com_person_id { get; set; }
        public string person_no { get; set; }
        public string person_name { get; set; }
        public string sex { get; set; }
        public System.DateTime birthday { get; set; }
        public string Dept_id { get; set; }
        public string dept_name { get; set; }
        public string title_name { get; set; }
        public Nullable<System.Guid> title_id { get; set; }
        public string unit { get; set; }
        public string person_state_name { get; set; }
        public string Other_no { get; set; }
        public string cert_id { get; set; }
        public Nullable<System.Guid> nation { get; set; }
        public Nullable<System.Guid> party { get; set; }
        public string university { get; set; }
        public string telephone { get; set; }
        public string mobile { get; set; }
        public string email { get; set; }
        public Nullable<System.Guid> spec { get; set; }
        public System.DateTime job_date { get; set; }
        public Nullable<System.Guid> education { get; set; }
        public Nullable<System.Guid> degree { get; set; }
        public string prof_cert_id { get; set; }
        public Nullable<System.Guid> hospital_duty { get; set; }
        public string photo { get; set; }
        public Nullable<System.Guid> person_type { get; set; }
        public string remark { get; set; }
        public string passwd { get; set; }
        public System.DateTime add_time { get; set; }
        public int Transfer_state { get; set; }
        public string nation_name { get; set; }
        public string party_name { get; set; }
        public string Spec_name { get; set; }
        public string education_name { get; set; }
        public string Degree_name { get; set; }
        public string hospital_duty_name { get; set; }
        public string internals { get; set; }
        public string unit_name { get; set; }
    }
}
