//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.17929
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 原始文件名:
// 生成日期: 2012/11/29 16:40:56
namespace HY.Frame.CMD.Remote
{
    
    /// <summary>
    /// 架构中不存在 DBEntities 的注释。
    /// </summary>
    public partial class DBEntities : global::System.Data.Services.Client.DataServiceContext
    {
        /// <summary>
        /// 初始化新的 DBEntities 对象。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public DBEntities(global::System.Uri serviceRoot) : 
                base(serviceRoot, global::System.Data.Services.Common.DataServiceProtocolVersion.V3)
        {
            this.ResolveName = new global::System.Func<global::System.Type, string>(this.ResolveNameFromType);
            this.ResolveType = new global::System.Func<string, global::System.Type>(this.ResolveTypeFromName);
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// 因为在 Visual Studio 中为此服务引用配置的
        /// 命名空间与在服务器架构中指示的命名空间不同，所以
        /// 使用类型映射器在这两者之间进行映射。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected global::System.Type ResolveTypeFromName(string typeName)
        {
            if (typeName.StartsWith("XXXX", global::System.StringComparison.Ordinal))
            {
                return this.GetType().Assembly.GetType(string.Concat("HY.Frame.CMD.Remote", typeName.Substring(4)), false);
            }
            return null;
        }
        /// <summary>
        /// 因为在 Visual Studio 中为此服务引用配置的
        /// 命名空间与在服务器架构中指示的命名空间不同，所以
        /// 使用类型映射器在这两者之间进行映射。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected string ResolveNameFromType(global::System.Type clientType)
        {
            if (clientType.Namespace.Equals("HY.Frame.CMD.Remote", global::System.StringComparison.Ordinal))
            {
                return string.Concat("XXXX.", clientType.Name);
            }
            return null;
        }
        /// <summary>
        /// 架构中不存在 com_person 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<com_person> com_person
        {
            get
            {
                if ((this._com_person == null))
                {
                    this._com_person = base.CreateQuery<com_person>("com_person");
                }
                return this._com_person;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<com_person> _com_person;
        /// <summary>
        /// 架构中不存在 com_person_view 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<com_person_view> com_person_view
        {
            get
            {
                if ((this._com_person_view == null))
                {
                    this._com_person_view = base.CreateQuery<com_person_view>("com_person_view");
                }
                return this._com_person_view;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<com_person_view> _com_person_view;
        /// <summary>
        /// 架构中不存在 com_person 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddTocom_person(com_person com_person)
        {
            base.AddObject("com_person", com_person);
        }
        /// <summary>
        /// 架构中不存在 com_person_view 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddTocom_person_view(com_person_view com_person_view)
        {
            base.AddObject("com_person_view", com_person_view);
        }
    }
    /// <summary>
    /// 架构中不存在 XXXX.com_person 的注释。
    /// </summary>
    /// <KeyProperties>
    /// com_person_id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("com_person")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("com_person_id")]
    public partial class com_person : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// 创建新的 com_person 对象。
        /// </summary>
        /// <param name="com_person_id">com_person_id 的初始值。</param>
        /// <param name="person_no">person_no 的初始值。</param>
        /// <param name="other_no">Other_no 的初始值。</param>
        /// <param name="person_name">person_name 的初始值。</param>
        /// <param name="sex">sex 的初始值。</param>
        /// <param name="cert_id">cert_id 的初始值。</param>
        /// <param name="birthday">birthday 的初始值。</param>
        /// <param name="university">university 的初始值。</param>
        /// <param name="telephone">telephone 的初始值。</param>
        /// <param name="mobile">mobile 的初始值。</param>
        /// <param name="email">email 的初始值。</param>
        /// <param name="job_date">job_date 的初始值。</param>
        /// <param name="prof_cert_id">prof_cert_id 的初始值。</param>
        /// <param name="photo">photo 的初始值。</param>
        /// <param name="remark">remark 的初始值。</param>
        /// <param name="passwd">passwd 的初始值。</param>
        /// <param name="dept_id">Dept_id 的初始值。</param>
        /// <param name="update_other_no">Update_other_no 的初始值。</param>
        /// <param name="transfer_state">Transfer_state 的初始值。</param>
        /// <param name="add_time">add_time 的初始值。</param>
        /// <param name="internals">internals 的初始值。</param>
        /// <param name="update_time">update_time 的初始值。</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static com_person Createcom_person(
                    global::System.Guid com_person_id, 
                    string person_no, 
                    string other_no, 
                    string person_name, 
                    string sex, 
                    string cert_id, 
                    global::System.DateTime birthday, 
                    string university, 
                    string telephone, 
                    string mobile, 
                    string email, 
                    global::System.DateTime job_date, 
                    string prof_cert_id, 
                    string photo, 
                    string remark, 
                    string passwd, 
                    string dept_id, 
                    byte update_other_no, 
                    int transfer_state, 
                    global::System.DateTime add_time, 
                    string internals, 
                    global::System.DateTime update_time)
        {
            com_person com_person = new com_person();
            com_person.com_person_id = com_person_id;
            com_person.person_no = person_no;
            com_person.Other_no = other_no;
            com_person.person_name = person_name;
            com_person.sex = sex;
            com_person.cert_id = cert_id;
            com_person.birthday = birthday;
            com_person.university = university;
            com_person.telephone = telephone;
            com_person.mobile = mobile;
            com_person.email = email;
            com_person.job_date = job_date;
            com_person.prof_cert_id = prof_cert_id;
            com_person.photo = photo;
            com_person.remark = remark;
            com_person.passwd = passwd;
            com_person.Dept_id = dept_id;
            com_person.Update_other_no = update_other_no;
            com_person.Transfer_state = transfer_state;
            com_person.add_time = add_time;
            com_person.internals = internals;
            com_person.update_time = update_time;
            return com_person;
        }
        /// <summary>
        /// 架构中不存在属性 com_person_id 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Guid com_person_id
        {
            get
            {
                return this._com_person_id;
            }
            set
            {
                this.Oncom_person_idChanging(value);
                this._com_person_id = value;
                this.Oncom_person_idChanged();
                this.OnPropertyChanged("com_person_id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Guid _com_person_id;
        partial void Oncom_person_idChanging(global::System.Guid value);
        partial void Oncom_person_idChanged();
        /// <summary>
        /// 架构中不存在属性 person_no 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string person_no
        {
            get
            {
                return this._person_no;
            }
            set
            {
                this.Onperson_noChanging(value);
                this._person_no = value;
                this.Onperson_noChanged();
                this.OnPropertyChanged("person_no");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _person_no;
        partial void Onperson_noChanging(string value);
        partial void Onperson_noChanged();
        /// <summary>
        /// 架构中不存在属性 Other_no 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Other_no
        {
            get
            {
                return this._Other_no;
            }
            set
            {
                this.OnOther_noChanging(value);
                this._Other_no = value;
                this.OnOther_noChanged();
                this.OnPropertyChanged("Other_no");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Other_no;
        partial void OnOther_noChanging(string value);
        partial void OnOther_noChanged();
        /// <summary>
        /// 架构中不存在属性 person_name 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string person_name
        {
            get
            {
                return this._person_name;
            }
            set
            {
                this.Onperson_nameChanging(value);
                this._person_name = value;
                this.Onperson_nameChanged();
                this.OnPropertyChanged("person_name");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _person_name;
        partial void Onperson_nameChanging(string value);
        partial void Onperson_nameChanged();
        /// <summary>
        /// 架构中不存在属性 sex 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string sex
        {
            get
            {
                return this._sex;
            }
            set
            {
                this.OnsexChanging(value);
                this._sex = value;
                this.OnsexChanged();
                this.OnPropertyChanged("sex");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _sex;
        partial void OnsexChanging(string value);
        partial void OnsexChanged();
        /// <summary>
        /// 架构中不存在属性 cert_id 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string cert_id
        {
            get
            {
                return this._cert_id;
            }
            set
            {
                this.Oncert_idChanging(value);
                this._cert_id = value;
                this.Oncert_idChanged();
                this.OnPropertyChanged("cert_id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _cert_id;
        partial void Oncert_idChanging(string value);
        partial void Oncert_idChanged();
        /// <summary>
        /// 架构中不存在属性 birthday 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.DateTime birthday
        {
            get
            {
                return this._birthday;
            }
            set
            {
                this.OnbirthdayChanging(value);
                this._birthday = value;
                this.OnbirthdayChanged();
                this.OnPropertyChanged("birthday");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.DateTime _birthday;
        partial void OnbirthdayChanging(global::System.DateTime value);
        partial void OnbirthdayChanged();
        /// <summary>
        /// 架构中不存在属性 nation 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<global::System.Guid> nation
        {
            get
            {
                return this._nation;
            }
            set
            {
                this.OnnationChanging(value);
                this._nation = value;
                this.OnnationChanged();
                this.OnPropertyChanged("nation");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<global::System.Guid> _nation;
        partial void OnnationChanging(global::System.Nullable<global::System.Guid> value);
        partial void OnnationChanged();
        /// <summary>
        /// 架构中不存在属性 party 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<global::System.Guid> party
        {
            get
            {
                return this._party;
            }
            set
            {
                this.OnpartyChanging(value);
                this._party = value;
                this.OnpartyChanged();
                this.OnPropertyChanged("party");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<global::System.Guid> _party;
        partial void OnpartyChanging(global::System.Nullable<global::System.Guid> value);
        partial void OnpartyChanged();
        /// <summary>
        /// 架构中不存在属性 university 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string university
        {
            get
            {
                return this._university;
            }
            set
            {
                this.OnuniversityChanging(value);
                this._university = value;
                this.OnuniversityChanged();
                this.OnPropertyChanged("university");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _university;
        partial void OnuniversityChanging(string value);
        partial void OnuniversityChanged();
        /// <summary>
        /// 架构中不存在属性 telephone 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string telephone
        {
            get
            {
                return this._telephone;
            }
            set
            {
                this.OntelephoneChanging(value);
                this._telephone = value;
                this.OntelephoneChanged();
                this.OnPropertyChanged("telephone");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _telephone;
        partial void OntelephoneChanging(string value);
        partial void OntelephoneChanged();
        /// <summary>
        /// 架构中不存在属性 mobile 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string mobile
        {
            get
            {
                return this._mobile;
            }
            set
            {
                this.OnmobileChanging(value);
                this._mobile = value;
                this.OnmobileChanged();
                this.OnPropertyChanged("mobile");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _mobile;
        partial void OnmobileChanging(string value);
        partial void OnmobileChanged();
        /// <summary>
        /// 架构中不存在属性 email 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string email
        {
            get
            {
                return this._email;
            }
            set
            {
                this.OnemailChanging(value);
                this._email = value;
                this.OnemailChanged();
                this.OnPropertyChanged("email");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _email;
        partial void OnemailChanging(string value);
        partial void OnemailChanged();
        /// <summary>
        /// 架构中不存在属性 spec 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<global::System.Guid> spec
        {
            get
            {
                return this._spec;
            }
            set
            {
                this.OnspecChanging(value);
                this._spec = value;
                this.OnspecChanged();
                this.OnPropertyChanged("spec");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<global::System.Guid> _spec;
        partial void OnspecChanging(global::System.Nullable<global::System.Guid> value);
        partial void OnspecChanged();
        /// <summary>
        /// 架构中不存在属性 job_date 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.DateTime job_date
        {
            get
            {
                return this._job_date;
            }
            set
            {
                this.Onjob_dateChanging(value);
                this._job_date = value;
                this.Onjob_dateChanged();
                this.OnPropertyChanged("job_date");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.DateTime _job_date;
        partial void Onjob_dateChanging(global::System.DateTime value);
        partial void Onjob_dateChanged();
        /// <summary>
        /// 架构中不存在属性 education 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<global::System.Guid> education
        {
            get
            {
                return this._education;
            }
            set
            {
                this.OneducationChanging(value);
                this._education = value;
                this.OneducationChanged();
                this.OnPropertyChanged("education");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<global::System.Guid> _education;
        partial void OneducationChanging(global::System.Nullable<global::System.Guid> value);
        partial void OneducationChanged();
        /// <summary>
        /// 架构中不存在属性 degree 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<global::System.Guid> degree
        {
            get
            {
                return this._degree;
            }
            set
            {
                this.OndegreeChanging(value);
                this._degree = value;
                this.OndegreeChanged();
                this.OnPropertyChanged("degree");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<global::System.Guid> _degree;
        partial void OndegreeChanging(global::System.Nullable<global::System.Guid> value);
        partial void OndegreeChanged();
        /// <summary>
        /// 架构中不存在属性 prof_cert_id 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string prof_cert_id
        {
            get
            {
                return this._prof_cert_id;
            }
            set
            {
                this.Onprof_cert_idChanging(value);
                this._prof_cert_id = value;
                this.Onprof_cert_idChanged();
                this.OnPropertyChanged("prof_cert_id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _prof_cert_id;
        partial void Onprof_cert_idChanging(string value);
        partial void Onprof_cert_idChanged();
        /// <summary>
        /// 架构中不存在属性 hospital_duty 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<global::System.Guid> hospital_duty
        {
            get
            {
                return this._hospital_duty;
            }
            set
            {
                this.Onhospital_dutyChanging(value);
                this._hospital_duty = value;
                this.Onhospital_dutyChanged();
                this.OnPropertyChanged("hospital_duty");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<global::System.Guid> _hospital_duty;
        partial void Onhospital_dutyChanging(global::System.Nullable<global::System.Guid> value);
        partial void Onhospital_dutyChanged();
        /// <summary>
        /// 架构中不存在属性 photo 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string photo
        {
            get
            {
                return this._photo;
            }
            set
            {
                this.OnphotoChanging(value);
                this._photo = value;
                this.OnphotoChanged();
                this.OnPropertyChanged("photo");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _photo;
        partial void OnphotoChanging(string value);
        partial void OnphotoChanged();
        /// <summary>
        /// 架构中不存在属性 person_type 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<global::System.Guid> person_type
        {
            get
            {
                return this._person_type;
            }
            set
            {
                this.Onperson_typeChanging(value);
                this._person_type = value;
                this.Onperson_typeChanged();
                this.OnPropertyChanged("person_type");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<global::System.Guid> _person_type;
        partial void Onperson_typeChanging(global::System.Nullable<global::System.Guid> value);
        partial void Onperson_typeChanged();
        /// <summary>
        /// 架构中不存在属性 remark 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string remark
        {
            get
            {
                return this._remark;
            }
            set
            {
                this.OnremarkChanging(value);
                this._remark = value;
                this.OnremarkChanged();
                this.OnPropertyChanged("remark");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _remark;
        partial void OnremarkChanging(string value);
        partial void OnremarkChanged();
        /// <summary>
        /// 架构中不存在属性 passwd 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string passwd
        {
            get
            {
                return this._passwd;
            }
            set
            {
                this.OnpasswdChanging(value);
                this._passwd = value;
                this.OnpasswdChanged();
                this.OnPropertyChanged("passwd");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _passwd;
        partial void OnpasswdChanging(string value);
        partial void OnpasswdChanged();
        /// <summary>
        /// 架构中不存在属性 Dept_id 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Dept_id
        {
            get
            {
                return this._Dept_id;
            }
            set
            {
                this.OnDept_idChanging(value);
                this._Dept_id = value;
                this.OnDept_idChanged();
                this.OnPropertyChanged("Dept_id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Dept_id;
        partial void OnDept_idChanging(string value);
        partial void OnDept_idChanged();
        /// <summary>
        /// 架构中不存在属性 Update_other_no 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public byte Update_other_no
        {
            get
            {
                return this._Update_other_no;
            }
            set
            {
                this.OnUpdate_other_noChanging(value);
                this._Update_other_no = value;
                this.OnUpdate_other_noChanged();
                this.OnPropertyChanged("Update_other_no");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private byte _Update_other_no;
        partial void OnUpdate_other_noChanging(byte value);
        partial void OnUpdate_other_noChanged();
        /// <summary>
        /// 架构中不存在属性 Transfer_state 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Transfer_state
        {
            get
            {
                return this._Transfer_state;
            }
            set
            {
                this.OnTransfer_stateChanging(value);
                this._Transfer_state = value;
                this.OnTransfer_stateChanged();
                this.OnPropertyChanged("Transfer_state");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Transfer_state;
        partial void OnTransfer_stateChanging(int value);
        partial void OnTransfer_stateChanged();
        /// <summary>
        /// 架构中不存在属性 add_time 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.DateTime add_time
        {
            get
            {
                return this._add_time;
            }
            set
            {
                this.Onadd_timeChanging(value);
                this._add_time = value;
                this.Onadd_timeChanged();
                this.OnPropertyChanged("add_time");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.DateTime _add_time;
        partial void Onadd_timeChanging(global::System.DateTime value);
        partial void Onadd_timeChanged();
        /// <summary>
        /// 架构中不存在属性 BatchGuid 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<global::System.Guid> BatchGuid
        {
            get
            {
                return this._BatchGuid;
            }
            set
            {
                this.OnBatchGuidChanging(value);
                this._BatchGuid = value;
                this.OnBatchGuidChanged();
                this.OnPropertyChanged("BatchGuid");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<global::System.Guid> _BatchGuid;
        partial void OnBatchGuidChanging(global::System.Nullable<global::System.Guid> value);
        partial void OnBatchGuidChanged();
        /// <summary>
        /// 架构中不存在属性 is_create_card 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<bool> is_create_card
        {
            get
            {
                return this._is_create_card;
            }
            set
            {
                this.Onis_create_cardChanging(value);
                this._is_create_card = value;
                this.Onis_create_cardChanged();
                this.OnPropertyChanged("is_create_card");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<bool> _is_create_card;
        partial void Onis_create_cardChanging(global::System.Nullable<bool> value);
        partial void Onis_create_cardChanged();
        /// <summary>
        /// 架构中不存在属性 is_charges 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<bool> is_charges
        {
            get
            {
                return this._is_charges;
            }
            set
            {
                this.Onis_chargesChanging(value);
                this._is_charges = value;
                this.Onis_chargesChanged();
                this.OnPropertyChanged("is_charges");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<bool> _is_charges;
        partial void Onis_chargesChanging(global::System.Nullable<bool> value);
        partial void Onis_chargesChanged();
        /// <summary>
        /// 架构中不存在属性 internals 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string internals
        {
            get
            {
                return this._internals;
            }
            set
            {
                this.OninternalsChanging(value);
                this._internals = value;
                this.OninternalsChanged();
                this.OnPropertyChanged("internals");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _internals;
        partial void OninternalsChanging(string value);
        partial void OninternalsChanged();
        /// <summary>
        /// 架构中不存在属性 update_time 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.DateTime update_time
        {
            get
            {
                return this._update_time;
            }
            set
            {
                this.Onupdate_timeChanging(value);
                this._update_time = value;
                this.Onupdate_timeChanged();
                this.OnPropertyChanged("update_time");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.DateTime _update_time;
        partial void Onupdate_timeChanging(global::System.DateTime value);
        partial void Onupdate_timeChanged();
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// 架构中不存在 XXXX.com_person_view 的注释。
    /// </summary>
    /// <KeyProperties>
    /// com_person_id
    /// person_no
    /// person_name
    /// sex
    /// birthday
    /// Dept_id
    /// Other_no
    /// cert_id
    /// university
    /// telephone
    /// mobile
    /// email
    /// job_date
    /// prof_cert_id
    /// photo
    /// remark
    /// passwd
    /// add_time
    /// Transfer_state
    /// internals
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("com_person_view")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("com_person_id", "person_no", "person_name", "sex", "birthday", "Dept_id", "Other_no", "cert_id", "university", "telephone", "mobile", "email", "job_date", "prof_cert_id", "photo", "remark", "passwd", "add_time", "Transfer_state", "internals")]
    public partial class com_person_view : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// 创建新的 com_person_view 对象。
        /// </summary>
        /// <param name="com_person_id">com_person_id 的初始值。</param>
        /// <param name="person_no">person_no 的初始值。</param>
        /// <param name="person_name">person_name 的初始值。</param>
        /// <param name="sex">sex 的初始值。</param>
        /// <param name="birthday">birthday 的初始值。</param>
        /// <param name="dept_id">Dept_id 的初始值。</param>
        /// <param name="other_no">Other_no 的初始值。</param>
        /// <param name="cert_id">cert_id 的初始值。</param>
        /// <param name="university">university 的初始值。</param>
        /// <param name="telephone">telephone 的初始值。</param>
        /// <param name="mobile">mobile 的初始值。</param>
        /// <param name="email">email 的初始值。</param>
        /// <param name="job_date">job_date 的初始值。</param>
        /// <param name="prof_cert_id">prof_cert_id 的初始值。</param>
        /// <param name="photo">photo 的初始值。</param>
        /// <param name="remark">remark 的初始值。</param>
        /// <param name="passwd">passwd 的初始值。</param>
        /// <param name="add_time">add_time 的初始值。</param>
        /// <param name="transfer_state">Transfer_state 的初始值。</param>
        /// <param name="internals">internals 的初始值。</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static com_person_view Createcom_person_view(
                    global::System.Guid com_person_id, 
                    string person_no, 
                    string person_name, 
                    string sex, 
                    global::System.DateTime birthday, 
                    string dept_id, 
                    string other_no, 
                    string cert_id, 
                    string university, 
                    string telephone, 
                    string mobile, 
                    string email, 
                    global::System.DateTime job_date, 
                    string prof_cert_id, 
                    string photo, 
                    string remark, 
                    string passwd, 
                    global::System.DateTime add_time, 
                    int transfer_state, 
                    string internals)
        {
            com_person_view com_person_view = new com_person_view();
            com_person_view.com_person_id = com_person_id;
            com_person_view.person_no = person_no;
            com_person_view.person_name = person_name;
            com_person_view.sex = sex;
            com_person_view.birthday = birthday;
            com_person_view.Dept_id = dept_id;
            com_person_view.Other_no = other_no;
            com_person_view.cert_id = cert_id;
            com_person_view.university = university;
            com_person_view.telephone = telephone;
            com_person_view.mobile = mobile;
            com_person_view.email = email;
            com_person_view.job_date = job_date;
            com_person_view.prof_cert_id = prof_cert_id;
            com_person_view.photo = photo;
            com_person_view.remark = remark;
            com_person_view.passwd = passwd;
            com_person_view.add_time = add_time;
            com_person_view.Transfer_state = transfer_state;
            com_person_view.internals = internals;
            return com_person_view;
        }
        /// <summary>
        /// 架构中不存在属性 com_person_id 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Guid com_person_id
        {
            get
            {
                return this._com_person_id;
            }
            set
            {
                this.Oncom_person_idChanging(value);
                this._com_person_id = value;
                this.Oncom_person_idChanged();
                this.OnPropertyChanged("com_person_id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Guid _com_person_id;
        partial void Oncom_person_idChanging(global::System.Guid value);
        partial void Oncom_person_idChanged();
        /// <summary>
        /// 架构中不存在属性 person_no 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string person_no
        {
            get
            {
                return this._person_no;
            }
            set
            {
                this.Onperson_noChanging(value);
                this._person_no = value;
                this.Onperson_noChanged();
                this.OnPropertyChanged("person_no");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _person_no;
        partial void Onperson_noChanging(string value);
        partial void Onperson_noChanged();
        /// <summary>
        /// 架构中不存在属性 person_name 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string person_name
        {
            get
            {
                return this._person_name;
            }
            set
            {
                this.Onperson_nameChanging(value);
                this._person_name = value;
                this.Onperson_nameChanged();
                this.OnPropertyChanged("person_name");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _person_name;
        partial void Onperson_nameChanging(string value);
        partial void Onperson_nameChanged();
        /// <summary>
        /// 架构中不存在属性 sex 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string sex
        {
            get
            {
                return this._sex;
            }
            set
            {
                this.OnsexChanging(value);
                this._sex = value;
                this.OnsexChanged();
                this.OnPropertyChanged("sex");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _sex;
        partial void OnsexChanging(string value);
        partial void OnsexChanged();
        /// <summary>
        /// 架构中不存在属性 birthday 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.DateTime birthday
        {
            get
            {
                return this._birthday;
            }
            set
            {
                this.OnbirthdayChanging(value);
                this._birthday = value;
                this.OnbirthdayChanged();
                this.OnPropertyChanged("birthday");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.DateTime _birthday;
        partial void OnbirthdayChanging(global::System.DateTime value);
        partial void OnbirthdayChanged();
        /// <summary>
        /// 架构中不存在属性 Dept_id 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Dept_id
        {
            get
            {
                return this._Dept_id;
            }
            set
            {
                this.OnDept_idChanging(value);
                this._Dept_id = value;
                this.OnDept_idChanged();
                this.OnPropertyChanged("Dept_id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Dept_id;
        partial void OnDept_idChanging(string value);
        partial void OnDept_idChanged();
        /// <summary>
        /// 架构中不存在属性 dept_name 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string dept_name
        {
            get
            {
                return this._dept_name;
            }
            set
            {
                this.Ondept_nameChanging(value);
                this._dept_name = value;
                this.Ondept_nameChanged();
                this.OnPropertyChanged("dept_name");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _dept_name;
        partial void Ondept_nameChanging(string value);
        partial void Ondept_nameChanged();
        /// <summary>
        /// 架构中不存在属性 title_name 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string title_name
        {
            get
            {
                return this._title_name;
            }
            set
            {
                this.Ontitle_nameChanging(value);
                this._title_name = value;
                this.Ontitle_nameChanged();
                this.OnPropertyChanged("title_name");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _title_name;
        partial void Ontitle_nameChanging(string value);
        partial void Ontitle_nameChanged();
        /// <summary>
        /// 架构中不存在属性 title_id 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<global::System.Guid> title_id
        {
            get
            {
                return this._title_id;
            }
            set
            {
                this.Ontitle_idChanging(value);
                this._title_id = value;
                this.Ontitle_idChanged();
                this.OnPropertyChanged("title_id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<global::System.Guid> _title_id;
        partial void Ontitle_idChanging(global::System.Nullable<global::System.Guid> value);
        partial void Ontitle_idChanged();
        /// <summary>
        /// 架构中不存在属性 unit 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string unit
        {
            get
            {
                return this._unit;
            }
            set
            {
                this.OnunitChanging(value);
                this._unit = value;
                this.OnunitChanged();
                this.OnPropertyChanged("unit");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _unit;
        partial void OnunitChanging(string value);
        partial void OnunitChanged();
        /// <summary>
        /// 架构中不存在属性 person_state_name 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string person_state_name
        {
            get
            {
                return this._person_state_name;
            }
            set
            {
                this.Onperson_state_nameChanging(value);
                this._person_state_name = value;
                this.Onperson_state_nameChanged();
                this.OnPropertyChanged("person_state_name");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _person_state_name;
        partial void Onperson_state_nameChanging(string value);
        partial void Onperson_state_nameChanged();
        /// <summary>
        /// 架构中不存在属性 Other_no 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Other_no
        {
            get
            {
                return this._Other_no;
            }
            set
            {
                this.OnOther_noChanging(value);
                this._Other_no = value;
                this.OnOther_noChanged();
                this.OnPropertyChanged("Other_no");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Other_no;
        partial void OnOther_noChanging(string value);
        partial void OnOther_noChanged();
        /// <summary>
        /// 架构中不存在属性 cert_id 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string cert_id
        {
            get
            {
                return this._cert_id;
            }
            set
            {
                this.Oncert_idChanging(value);
                this._cert_id = value;
                this.Oncert_idChanged();
                this.OnPropertyChanged("cert_id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _cert_id;
        partial void Oncert_idChanging(string value);
        partial void Oncert_idChanged();
        /// <summary>
        /// 架构中不存在属性 nation 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<global::System.Guid> nation
        {
            get
            {
                return this._nation;
            }
            set
            {
                this.OnnationChanging(value);
                this._nation = value;
                this.OnnationChanged();
                this.OnPropertyChanged("nation");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<global::System.Guid> _nation;
        partial void OnnationChanging(global::System.Nullable<global::System.Guid> value);
        partial void OnnationChanged();
        /// <summary>
        /// 架构中不存在属性 party 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<global::System.Guid> party
        {
            get
            {
                return this._party;
            }
            set
            {
                this.OnpartyChanging(value);
                this._party = value;
                this.OnpartyChanged();
                this.OnPropertyChanged("party");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<global::System.Guid> _party;
        partial void OnpartyChanging(global::System.Nullable<global::System.Guid> value);
        partial void OnpartyChanged();
        /// <summary>
        /// 架构中不存在属性 university 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string university
        {
            get
            {
                return this._university;
            }
            set
            {
                this.OnuniversityChanging(value);
                this._university = value;
                this.OnuniversityChanged();
                this.OnPropertyChanged("university");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _university;
        partial void OnuniversityChanging(string value);
        partial void OnuniversityChanged();
        /// <summary>
        /// 架构中不存在属性 telephone 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string telephone
        {
            get
            {
                return this._telephone;
            }
            set
            {
                this.OntelephoneChanging(value);
                this._telephone = value;
                this.OntelephoneChanged();
                this.OnPropertyChanged("telephone");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _telephone;
        partial void OntelephoneChanging(string value);
        partial void OntelephoneChanged();
        /// <summary>
        /// 架构中不存在属性 mobile 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string mobile
        {
            get
            {
                return this._mobile;
            }
            set
            {
                this.OnmobileChanging(value);
                this._mobile = value;
                this.OnmobileChanged();
                this.OnPropertyChanged("mobile");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _mobile;
        partial void OnmobileChanging(string value);
        partial void OnmobileChanged();
        /// <summary>
        /// 架构中不存在属性 email 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string email
        {
            get
            {
                return this._email;
            }
            set
            {
                this.OnemailChanging(value);
                this._email = value;
                this.OnemailChanged();
                this.OnPropertyChanged("email");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _email;
        partial void OnemailChanging(string value);
        partial void OnemailChanged();
        /// <summary>
        /// 架构中不存在属性 spec 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<global::System.Guid> spec
        {
            get
            {
                return this._spec;
            }
            set
            {
                this.OnspecChanging(value);
                this._spec = value;
                this.OnspecChanged();
                this.OnPropertyChanged("spec");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<global::System.Guid> _spec;
        partial void OnspecChanging(global::System.Nullable<global::System.Guid> value);
        partial void OnspecChanged();
        /// <summary>
        /// 架构中不存在属性 job_date 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.DateTime job_date
        {
            get
            {
                return this._job_date;
            }
            set
            {
                this.Onjob_dateChanging(value);
                this._job_date = value;
                this.Onjob_dateChanged();
                this.OnPropertyChanged("job_date");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.DateTime _job_date;
        partial void Onjob_dateChanging(global::System.DateTime value);
        partial void Onjob_dateChanged();
        /// <summary>
        /// 架构中不存在属性 education 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<global::System.Guid> education
        {
            get
            {
                return this._education;
            }
            set
            {
                this.OneducationChanging(value);
                this._education = value;
                this.OneducationChanged();
                this.OnPropertyChanged("education");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<global::System.Guid> _education;
        partial void OneducationChanging(global::System.Nullable<global::System.Guid> value);
        partial void OneducationChanged();
        /// <summary>
        /// 架构中不存在属性 degree 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<global::System.Guid> degree
        {
            get
            {
                return this._degree;
            }
            set
            {
                this.OndegreeChanging(value);
                this._degree = value;
                this.OndegreeChanged();
                this.OnPropertyChanged("degree");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<global::System.Guid> _degree;
        partial void OndegreeChanging(global::System.Nullable<global::System.Guid> value);
        partial void OndegreeChanged();
        /// <summary>
        /// 架构中不存在属性 prof_cert_id 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string prof_cert_id
        {
            get
            {
                return this._prof_cert_id;
            }
            set
            {
                this.Onprof_cert_idChanging(value);
                this._prof_cert_id = value;
                this.Onprof_cert_idChanged();
                this.OnPropertyChanged("prof_cert_id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _prof_cert_id;
        partial void Onprof_cert_idChanging(string value);
        partial void Onprof_cert_idChanged();
        /// <summary>
        /// 架构中不存在属性 hospital_duty 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<global::System.Guid> hospital_duty
        {
            get
            {
                return this._hospital_duty;
            }
            set
            {
                this.Onhospital_dutyChanging(value);
                this._hospital_duty = value;
                this.Onhospital_dutyChanged();
                this.OnPropertyChanged("hospital_duty");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<global::System.Guid> _hospital_duty;
        partial void Onhospital_dutyChanging(global::System.Nullable<global::System.Guid> value);
        partial void Onhospital_dutyChanged();
        /// <summary>
        /// 架构中不存在属性 photo 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string photo
        {
            get
            {
                return this._photo;
            }
            set
            {
                this.OnphotoChanging(value);
                this._photo = value;
                this.OnphotoChanged();
                this.OnPropertyChanged("photo");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _photo;
        partial void OnphotoChanging(string value);
        partial void OnphotoChanged();
        /// <summary>
        /// 架构中不存在属性 person_type 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<global::System.Guid> person_type
        {
            get
            {
                return this._person_type;
            }
            set
            {
                this.Onperson_typeChanging(value);
                this._person_type = value;
                this.Onperson_typeChanged();
                this.OnPropertyChanged("person_type");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<global::System.Guid> _person_type;
        partial void Onperson_typeChanging(global::System.Nullable<global::System.Guid> value);
        partial void Onperson_typeChanged();
        /// <summary>
        /// 架构中不存在属性 remark 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string remark
        {
            get
            {
                return this._remark;
            }
            set
            {
                this.OnremarkChanging(value);
                this._remark = value;
                this.OnremarkChanged();
                this.OnPropertyChanged("remark");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _remark;
        partial void OnremarkChanging(string value);
        partial void OnremarkChanged();
        /// <summary>
        /// 架构中不存在属性 passwd 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string passwd
        {
            get
            {
                return this._passwd;
            }
            set
            {
                this.OnpasswdChanging(value);
                this._passwd = value;
                this.OnpasswdChanged();
                this.OnPropertyChanged("passwd");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _passwd;
        partial void OnpasswdChanging(string value);
        partial void OnpasswdChanged();
        /// <summary>
        /// 架构中不存在属性 add_time 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.DateTime add_time
        {
            get
            {
                return this._add_time;
            }
            set
            {
                this.Onadd_timeChanging(value);
                this._add_time = value;
                this.Onadd_timeChanged();
                this.OnPropertyChanged("add_time");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.DateTime _add_time;
        partial void Onadd_timeChanging(global::System.DateTime value);
        partial void Onadd_timeChanged();
        /// <summary>
        /// 架构中不存在属性 Transfer_state 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Transfer_state
        {
            get
            {
                return this._Transfer_state;
            }
            set
            {
                this.OnTransfer_stateChanging(value);
                this._Transfer_state = value;
                this.OnTransfer_stateChanged();
                this.OnPropertyChanged("Transfer_state");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Transfer_state;
        partial void OnTransfer_stateChanging(int value);
        partial void OnTransfer_stateChanged();
        /// <summary>
        /// 架构中不存在属性 nation_name 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string nation_name
        {
            get
            {
                return this._nation_name;
            }
            set
            {
                this.Onnation_nameChanging(value);
                this._nation_name = value;
                this.Onnation_nameChanged();
                this.OnPropertyChanged("nation_name");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _nation_name;
        partial void Onnation_nameChanging(string value);
        partial void Onnation_nameChanged();
        /// <summary>
        /// 架构中不存在属性 party_name 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string party_name
        {
            get
            {
                return this._party_name;
            }
            set
            {
                this.Onparty_nameChanging(value);
                this._party_name = value;
                this.Onparty_nameChanged();
                this.OnPropertyChanged("party_name");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _party_name;
        partial void Onparty_nameChanging(string value);
        partial void Onparty_nameChanged();
        /// <summary>
        /// 架构中不存在属性 Spec_name 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Spec_name
        {
            get
            {
                return this._Spec_name;
            }
            set
            {
                this.OnSpec_nameChanging(value);
                this._Spec_name = value;
                this.OnSpec_nameChanged();
                this.OnPropertyChanged("Spec_name");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Spec_name;
        partial void OnSpec_nameChanging(string value);
        partial void OnSpec_nameChanged();
        /// <summary>
        /// 架构中不存在属性 education_name 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string education_name
        {
            get
            {
                return this._education_name;
            }
            set
            {
                this.Oneducation_nameChanging(value);
                this._education_name = value;
                this.Oneducation_nameChanged();
                this.OnPropertyChanged("education_name");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _education_name;
        partial void Oneducation_nameChanging(string value);
        partial void Oneducation_nameChanged();
        /// <summary>
        /// 架构中不存在属性 Degree_name 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Degree_name
        {
            get
            {
                return this._Degree_name;
            }
            set
            {
                this.OnDegree_nameChanging(value);
                this._Degree_name = value;
                this.OnDegree_nameChanged();
                this.OnPropertyChanged("Degree_name");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Degree_name;
        partial void OnDegree_nameChanging(string value);
        partial void OnDegree_nameChanged();
        /// <summary>
        /// 架构中不存在属性 hospital_duty_name 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string hospital_duty_name
        {
            get
            {
                return this._hospital_duty_name;
            }
            set
            {
                this.Onhospital_duty_nameChanging(value);
                this._hospital_duty_name = value;
                this.Onhospital_duty_nameChanged();
                this.OnPropertyChanged("hospital_duty_name");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _hospital_duty_name;
        partial void Onhospital_duty_nameChanging(string value);
        partial void Onhospital_duty_nameChanged();
        /// <summary>
        /// 架构中不存在属性 internals 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string internals
        {
            get
            {
                return this._internals;
            }
            set
            {
                this.OninternalsChanging(value);
                this._internals = value;
                this.OninternalsChanged();
                this.OnPropertyChanged("internals");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _internals;
        partial void OninternalsChanging(string value);
        partial void OninternalsChanged();
        /// <summary>
        /// 架构中不存在属性 unit_name 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string unit_name
        {
            get
            {
                return this._unit_name;
            }
            set
            {
                this.Onunit_nameChanging(value);
                this._unit_name = value;
                this.Onunit_nameChanged();
                this.OnPropertyChanged("unit_name");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _unit_name;
        partial void Onunit_nameChanging(string value);
        partial void Onunit_nameChanged();
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
}
