

/*//////////////////////////////////////////////////////////////////////////////////////
////// Autogenerated by JaySvcUtil.exe http://JayData.org for more info        /////////
//////                             oData V2                                    /////////
//////////////////////////////////////////////////////////////////////////////////////*/
(function(global, $data, undefined) {

  $data.Entity.extend('XXXX.com_person', {
    'com_person_id': { 'key':true,'type':'Edm.Guid','nullable':false,'required':true },
    'person_no': { 'type':'Edm.String','nullable':false,'required':true,'maxLength':10 },
    'Other_no': { 'type':'Edm.String','nullable':false,'required':true,'maxLength':20 },
    'person_name': { 'type':'Edm.String','nullable':false,'required':true,'maxLength':40 },
    'sex': { 'type':'Edm.String','nullable':false,'required':true,'maxLength':2 },
    'cert_id': { 'type':'Edm.String','nullable':false,'required':true,'maxLength':18 },
    'birthday': { 'type':'Edm.DateTime','nullable':false,'required':true },
    'nation': { 'type':'Edm.Guid' },
    'party': { 'type':'Edm.Guid' },
    'university': { 'type':'Edm.String','nullable':false,'required':true,'maxLength':50 },
    'telephone': { 'type':'Edm.String','nullable':false,'required':true,'maxLength':50 },
    'mobile': { 'type':'Edm.String','nullable':false,'required':true,'maxLength':50 },
    'email': { 'type':'Edm.String','nullable':false,'required':true,'maxLength':50 },
    'spec': { 'type':'Edm.Guid' },
    'job_date': { 'type':'Edm.DateTime','nullable':false,'required':true },
    'education': { 'type':'Edm.Guid' },
    'degree': { 'type':'Edm.Guid' },
    'prof_cert_id': { 'type':'Edm.String','nullable':false,'required':true,'maxLength':50 },
    'hospital_duty': { 'type':'Edm.Guid' },
    'photo': { 'type':'Edm.String','nullable':false,'required':true,'maxLength':200 },
    'person_type': { 'type':'Edm.Guid' },
    'remark': { 'type':'Edm.String','nullable':false,'required':true,'maxLength':200 },
    'passwd': { 'type':'Edm.String','nullable':false,'required':true,'maxLength':20 },
    'Dept_id': { 'type':'Edm.String','nullable':false,'required':true,'maxLength':9 },
    'Update_other_no': { 'type':'Edm.Byte','nullable':false,'required':true },
    'Transfer_state': { 'type':'Edm.Int32','nullable':false,'required':true },
    'add_time': { 'type':'Edm.DateTime','nullable':false,'required':true },
    'BatchGuid': { 'type':'Edm.Guid' },
    'is_create_card': { 'type':'Edm.Boolean' },
    'is_charges': { 'type':'Edm.Boolean' },
    'internals': { 'type':'Edm.String','nullable':false,'required':true,'maxLength':30 },
    'update_time': { 'type':'Edm.DateTime','nullable':false,'required':true }
  });
  
  $data.Entity.extend('XXXX.com_person_view', {
    'com_person_id': { 'key':true,'type':'Edm.Guid','nullable':false,'required':true },
    'person_no': { 'key':true,'type':'Edm.String','nullable':false,'required':true,'maxLength':10 },
    'person_name': { 'key':true,'type':'Edm.String','nullable':false,'required':true,'maxLength':40 },
    'sex': { 'key':true,'type':'Edm.String','nullable':false,'required':true,'maxLength':2 },
    'birthday': { 'key':true,'type':'Edm.DateTime','nullable':false,'required':true },
    'Dept_id': { 'key':true,'type':'Edm.String','nullable':false,'required':true,'maxLength':9 },
    'dept_name': { 'type':'Edm.String','maxLength':100 },
    'title_name': { 'type':'Edm.String','maxLength':50 },
    'title_id': { 'type':'Edm.Guid' },
    'unit': { 'type':'Edm.String','maxLength':6 },
    'person_state_name': { 'type':'Edm.String','maxLength':20 },
    'Other_no': { 'key':true,'type':'Edm.String','nullable':false,'required':true,'maxLength':20 },
    'cert_id': { 'key':true,'type':'Edm.String','nullable':false,'required':true,'maxLength':18 },
    'nation': { 'type':'Edm.Guid' },
    'party': { 'type':'Edm.Guid' },
    'university': { 'key':true,'type':'Edm.String','nullable':false,'required':true,'maxLength':50 },
    'telephone': { 'key':true,'type':'Edm.String','nullable':false,'required':true,'maxLength':50 },
    'mobile': { 'key':true,'type':'Edm.String','nullable':false,'required':true,'maxLength':50 },
    'email': { 'key':true,'type':'Edm.String','nullable':false,'required':true,'maxLength':50 },
    'spec': { 'type':'Edm.Guid' },
    'job_date': { 'key':true,'type':'Edm.DateTime','nullable':false,'required':true },
    'education': { 'type':'Edm.Guid' },
    'degree': { 'type':'Edm.Guid' },
    'prof_cert_id': { 'key':true,'type':'Edm.String','nullable':false,'required':true,'maxLength':50 },
    'hospital_duty': { 'type':'Edm.Guid' },
    'photo': { 'key':true,'type':'Edm.String','nullable':false,'required':true,'maxLength':200 },
    'person_type': { 'type':'Edm.Guid' },
    'remark': { 'key':true,'type':'Edm.String','nullable':false,'required':true,'maxLength':200 },
    'passwd': { 'key':true,'type':'Edm.String','nullable':false,'required':true,'maxLength':20 },
    'add_time': { 'key':true,'type':'Edm.DateTime','nullable':false,'required':true },
    'Transfer_state': { 'key':true,'type':'Edm.Int32','nullable':false,'required':true },
    'nation_name': { 'type':'Edm.String','maxLength':100 },
    'party_name': { 'type':'Edm.String','maxLength':100 },
    'Spec_name': { 'type':'Edm.String','maxLength':100 },
    'education_name': { 'type':'Edm.String','maxLength':100 },
    'Degree_name': { 'type':'Edm.String','maxLength':100 },
    'hospital_duty_name': { 'type':'Edm.String','maxLength':100 },
    'internals': { 'key':true,'type':'Edm.String','nullable':false,'required':true,'maxLength':30 },
    'unit_name': { 'type':'Edm.String','maxLength':100 }
  });
  
  $data.EntityContext.extend('HY.Frame.Bis.DBEntities', {
    'com_person': { type: $data.EntitySet, elementType: XXXX.com_person },
    'com_person_view': { type: $data.EntitySet, elementType: XXXX.com_person_view }
  });

  $data.generatedContexts = $data.generatedContexts || [];
  $data.generatedContexts.push(HY.Frame.Bis.DBEntities);
  
  /*Context Instance*/
  HY.Frame.Bis.context = new HY.Frame.Bis.DBEntities( { name:'oData', oDataServiceHost: 'http://localhost:27204/DS.svc' });

      
})(window, $data);
      
    